#!/usr/bin/env node
/** Copies the few browser libraries and fonts the local UI needs (no CDN at runtime). */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const nm = (...p) => path.join(root, 'node_modules', ...p);
const vendor = path.join(root, 'src/renderer/vendor');
const fonts = path.join(root, 'src/renderer/fonts');
fs.mkdirSync(vendor, { recursive: true });
fs.mkdirSync(fonts, { recursive: true });

const copy = (from, to) => { fs.copyFileSync(from, to); console.log('  ', path.relative(root, to)); };

copy(nm('marked/lib/marked.umd.js'), path.join(vendor, 'marked.js'));
copy(nm('dompurify/dist/purify.min.js'), path.join(vendor, 'purify.js'));

// highlight.js: the prebuilt common bundle is not shipped in the npm package, so build a
// small UMD from the core + the languages people actually use.
const hl = require(nm('highlight.js/lib/core'));
const langs = ['javascript', 'typescript', 'json', 'xml', 'css', 'scss', 'python', 'bash', 'shell', 'markdown',
  'yaml', 'sql', 'go', 'rust', 'java', 'kotlin', 'swift', 'c', 'cpp', 'csharp', 'php', 'ruby', 'dockerfile',
  'ini', 'diff', 'plaintext', 'powershell', 'lua', 'dart'];
let bundle = '/* highlight.js core + selected languages (generated by scripts/vendor-assets.js) */\n(function(){\n';
bundle += 'var module = { exports: {} }, exports = module.exports;\n';
bundle += fs.readFileSync(nm('highlight.js/lib/core.js'), 'utf8') + '\n';
bundle += 'var hljs = module.exports; window.hljs = hljs;\n';
for (const l of langs) {
  const file = nm('highlight.js/lib/languages', `${l}.js`);
  if (!fs.existsSync(file)) continue;
  bundle += `(function(){ var module = { exports: {} }, exports = module.exports;\n${fs.readFileSync(file, 'utf8')}\n hljs.registerLanguage(${JSON.stringify(l)}, module.exports); })();\n`;
}
bundle += '})();\n';
fs.writeFileSync(path.join(vendor, 'highlight.js'), bundle);
console.log('   src/renderer/vendor/highlight.js', langs.length, 'languages');
void hl;

const fontFiles = [
  ['@fontsource-variable/inter/files/inter-latin-wght-normal.woff2', 'inter-latin.woff2'],
  ['@fontsource-variable/inter/files/inter-latin-ext-wght-normal.woff2', 'inter-latin-ext.woff2'],
  ['@fontsource-variable/playfair-display/files/playfair-display-latin-wght-normal.woff2', 'playfair-latin.woff2'],
  ['@fontsource-variable/playfair-display/files/playfair-display-latin-wght-italic.woff2', 'playfair-latin-italic.woff2'],
  ['@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-wght-normal.woff2', 'jetbrains-mono-latin.woff2'],
];
for (const [from, to] of fontFiles) copy(nm(from), path.join(fonts, to));
